### ISSUE TITLE
PYTHON调用crf分词，参考您class crfSegment(Resource)代码中的例子，有报错，希望您指点一下

### ISSUE THREAD

**Issue by guduxingzou** [yesseecity/hanLP-python-flask#1]
from jpype import *
startJVM(getDefaultJVMPath(), "-Djava.class.path=C:\hanlp\hanlp-1.3.2.jar;C:\hanlp", "-Xms1g", "-Xmx1g") # 启动JVM，Linux需替换分号;为冒号:
CRFSegment = JClass('com.hankcs.hanlp.seg.CRF.CRFSegment')
segemntTool = CRFSegment().seg
content='你好，我好，大家好'
segemntTool(content)## #此句报错_

Traceback (most recent call last):

  File "<ipython-input-18-b48e9bd55ac4>", line 7, in <module>
    segemntTool(content)# #此句报错_

RuntimeError: Multiple overloads possible. at native\common\jp_method.cpp:109
 
盼复，非常感谢！

**Comment by yesseecity** [comment]
其他分詞器能正常使用嗎？

**Comment by guduxingzou** [comment]
@yesseecity  是的 其他的都测试成功了，就这个不成功！
谢谢您的回复！

**Comment by yesseecity** [comment]
我在docker 內的環境測試是正常的(Linux)，晚上下班後我再找台windows來測試

**Comment by guduxingzou** [comment]
非常感谢您，谢谢

**Comment by yesseecity** [comment]
我在windows 上用docker 去跑是正常的，要不要試試看用docker 執行？

**Comment by guduxingzou** [comment]
搜嘎  我的电脑之前安装docker失败了，那我试试在Linux系统下能不能用吧？如果是这样子的话，有没有可能是因为操作系统引起？

**Comment by yesseecity** [comment]
不排除這個可能，畢竟每個人的電腦都不同

**Comment by guduxingzou** [comment]
嗯嗯 好的！
